### ISSUE TITLE
Need SEO

### ISSUE THREAD

**Issue by florent1933** [Atilla106/atilla.org#1]

**Comment by Thooms** [comment]
@florent1933 @MrChoclate @neeev you guys are the only ones that know something about SEO, mind taking care of it?

**Comment by florent1933** [comment]
I can close this issue but only in 2 weeks. 

Maybe someone can taking care of this issue before me.

**Comment by Thooms** [comment]
Closing, since no one is gonna work on it anytime soon. Let's reopen if the need for SEO comes again later.
