### ISSUE TITLE
Migrate project to gitlab.atilla.org

### ISSUE THREAD

**Issue by aubincleme** [Atilla106/atilla.org#48]
We now have a super open source platform for hosting our projects : gitlab.atilla.org
Thereby, we should migrate this project to a new repository on gitlab.atilla.org and configure the GH repo to be a simple mirror.

Awaiting approval of @Kirogo for migration …

**Comment by florent1933** [comment]
@aubincleme, can we close this issue?

**Comment by aubincleme** [comment]
@florent1933, yes, the migration has been done last February.
