### ISSUE TITLE
Update services

### ISSUE THREAD

**Issue by florent1933** [Atilla106/atilla.org#6]
kan.atilla.org

**Comment by florent1933** [comment]
paste.atilla.org
pad.atilla.org
doc.atilla.org
rer.atilla.org
edt.atilla.org
Others? @Atilla106/core

**Comment by flavray** [comment]
multiboard.atilla.org

**Comment by flavray** [comment]
blog.atilla.org ?
learn.atilla.org ?

**Comment by AntoineGirard** [comment]
Update in #20
